using Application;
using Application.Core.Models;
using Application.Core.Responses;
using Infrastructure;
using Infrastructure.Data;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using Presentation;
using System.Text;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
	c.SwaggerDoc("v1", new OpenApiInfo
	{
		Version = "v1",
		Title = "TaskManager API",
	});



    // JWT Auth
    c.AddSecurityDefinition(JwtBearerDefaults.AuthenticationScheme,
    new OpenApiSecurityScheme
    {
        Name = "Authorization",
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT",
        In = ParameterLocation.Header,
        Description = "Enter only the JWT token."
    });

    c.AddSecurityRequirement(new OpenApiSecurityRequirement
{
    {
        new OpenApiSecurityScheme
        {
            Reference = new OpenApiReference
            {
                Type = ReferenceType.SecurityScheme,
                Id = JwtBearerDefaults.AuthenticationScheme
            }
        },
        Array.Empty<string>()
    }
});

});

//add application and infrastructre injections.
builder.Services.AddInfrastructureServices(builder.Configuration);
builder.Services.AddApplicationServices();

// make all tokens generated by  asp.net like emailconfirmation and resetPassword token to expired after specific time
builder.Services.Configure<DataProtectionTokenProviderOptions>(options =>
{
	options.TokenLifespan = TimeSpan.FromHours(1); // or 2 days etc.
});

//configure jwtOptions to bind its values from jwt section in appsettings.json
builder.Services.AddOptions<JWTOptions>()
	.BindConfiguration(JWTOptions.SectionName)
	.ValidateDataAnnotations()
	.ValidateOnStart();

var jwtOptions = builder.Configuration.GetSection(JWTOptions.SectionName).Get<JWTOptions>();

builder.Services.AddAuthentication(options =>
{
	options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
	options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
	options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(options =>
{
	options.SaveToken = true;
	options.RequireHttpsMetadata = true;
	options.TokenValidationParameters = new TokenValidationParameters()
	{
		ValidateIssuerSigningKey = true,
		ValidateLifetime = true,
		ValidateIssuer = true,
		ValidIssuer = jwtOptions?.Issuer,
		ValidateAudience = true,
		ValidAudience = jwtOptions?.Audience,
		IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtOptions?.Key!))
	};
});


//configure validation error to be in the standard error response 
builder.Services.Configure<ApiBehaviorOptions>(options =>
{
	options.InvalidModelStateResponseFactory = (actionContext) =>
	{
		var errors = actionContext.ModelState.Where(p => p.Value?.Errors.Count > 0)
											 .SelectMany(p => p.Value?.Errors ?? Enumerable.Empty<ModelError>())
											 .Select(E => E.ErrorMessage)
											 .ToList();
		var response = new ValidationErrorResponse
		{
			Errors = errors
		};

		return new BadRequestObjectResult(response);
	};
});

builder.Services.AddHttpContextAccessor();

//Add CORS
builder.Services.AddCors(options =>
{
	options.AddPolicy("AllowAnyOrigin",
		policy =>
		{
			policy.AllowAnyOrigin()
				  .AllowAnyHeader()
				  .AllowAnyMethod();
		});
});

// health check
builder.Services.AddHealthChecks();

//global exception handler
builder.Services.AddExceptionHandler<GlobalExceptionHandler>();

builder.Services.AddProblemDetails();

var app = builder.Build();

using (var _scop = app.Services.CreateScope())
{

	var serviceProvider = _scop.ServiceProvider;
	var context = serviceProvider.GetRequiredService<ApplicationDbContext>();
	var logerfactory = serviceProvider.GetRequiredService<ILoggerFactory>();

	try
	{
		if (app.Environment.IsProduction())
		{
			//Apply Migrations
			await context.Database.MigrateAsync().ConfigureAwait(0);
		}
	}
	catch (Exception ex)
	{
		var loger = logerfactory.CreateLogger<Program>();
		loger.LogError(ex, "an error occured while applying migrations.");
	}

}

app.UseExceptionHandler();
// Configure the HTTP request pipeline.
var swaggerUser = builder.Configuration["Swagger:Username"];
var swaggerPassword = builder.Configuration["Swagger:Password"];

app.UseSwagger();
app.UseSwaggerUI();

app.UseCors("AllowAnyOrigin");
app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.MapHealthChecks("health");

app.Run();
